/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_diy_HelloTest */

#ifndef _Included_com_example_diy_HelloTest
#define _Included_com_example_diy_HelloTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_diy_HelloTest
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_diy_HelloTest_getName
  (JNIEnv *, jclass);

/*
 * Class:     com_example_diy_HelloTest
 * Method:    getStart
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_diy_HelloTest_getStart
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
